---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "31"
year: "2017"
contributor: 
- "Karsten Schuldt"
title: "Vom Werden und Vergehen der Bibliotheken in Berliner Schulen"
subtitle: "Die Entwicklung der Schulbibliotheken in Berlin 2008-2017 und
    Konsequenzen für Forschung und Bibliothekspolitik"
date: 2017-07-20 22:00
comments: false
sharing: true
footer: true

---