---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "31"
year: "2017"
contributor: 
- "Redaktion LIBREAS"
title: "Editorial #30: Emotion(al Labor)"
urn: "urn:nbn:de:kobv:11-110-18452/19662-0"
date: 2017-07-20 22:00
comments: false
sharing: true
footer: true

---