---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "31"
year: "2017"
contributor: 
- "Linda Freyberg"
- "Ben Kaden"
title: "Ein Ortsbesuch im Prenzlauer Berg. Eine Reportage basierend auf einem Interview mit Danilo Vetter"
urn: "urn:nbn:de:kobv:11-110-18452/19667-0"
date: 2017-07-20 22:00
comments: false
sharing: true
footer: true

---