---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "31"
year: "2017"
contributor: 
- "Susanne Brandt"
title: "Entspannt euch!"
subtitle: "Ein Kommentar zur Emotionalität in aktuellen bibliothekarischen Debatten"
urn: "urn:nbn:de:kobv:11-110-18452/19664-2"
date: 2014-07-19 20:00
comments: false
sharing: true
footer: true

---