---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "31"
year: "2017"
contributor: 
- "Susanne Brandt"
title: "<q>Lesen, dass ein anderer ebenso fühlt.</q> Die
    Janusz-Korczak-Geschwisterbücherei"
urn: "urn:nbn:de:kobv:11-110-18452/19665-8"
date: 2014-07-19 20:00
comments: false
sharing: true
footer: true

---