---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "31"
year: "2017"
contributor: 
- "Linda Freyberg"
- "Ben Kaden"
title: "Buch, Karow. Ein Ortstermin in zwei Berliner öffentlichen Bibliotheken"
date: 2017-07-20 22:00
comments: false
sharing: true
footer: true

---