---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "31"
year: "2017"
contributor: 
- "Juliane Waack"
title: "Meine Bibliothek. Eine Erinnerung."
subtitle: ""
date: 2014-07-19 20:00
comments: false
sharing: true
footer: true

---