---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "31"
year: "2017"
contributor: 
- "Najko Jahn"
- "Ben Kaden"
title: "Notiz zum Titelbild"
subtitle: "Über den Versuch, Stimmungen innerhalb von Kommentaren der Initiative Publikationsfreiheit zu bemessen"
urn: "urn:nbn:de:kobv:11-110-18452/19663-6"
date: 2017-07-20 22:00
comments: false
sharing: true
footer: true

---