---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "31"
year: "2017"
contributor: 
- "Ben Kaden"
title: "Shoebox Science Kits und 155 weitere Bibliotheksideen aus dem Jahr 1977"
subtitle: "Rezension zu: Dale E. Schaffer, Public Collectors (2017 [1977]): LIBRARY EXCAVATIONS #5: A HANDBOOK OF LIBRARY IDEAS. Chicago, Il: Public Collectors, 40 Seiten, 6 $"
date: 2017-07-20 22:00
comments: false
sharing: true
footer: true

---